apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: V-Books
spec:
  replicas: 3
  selector:
    matchLabels:
      app: V-Books
      tier: backend
      track: stable
  template:
    metadata:
      labels:
        app: V-Books
        tier: backend
        track: stable
    spec:
      containers:
        - name: api
          image: copsfuraxx/devops:api
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
